"use client";

import { FormEvent, useEffect, useState } from "react";
import { BookOpen, CheckCircle2, Plus, Scale, Trash2 } from "lucide-react";
import { AddButton, apiRequest, EmptyState, LoadingPanel, Modal, Notice, PageHeader, StatusPill, useNotice } from "@/components/ui";
import { useBusiness } from "@/components/business-context";

type Account = { _id: string; code: string; name: string; type: string };
type Line = { account: string; debit: number; credit: number };
type Entry = { _id: string; entryNo: string; date: string; memo: string; reference: string; source: string; status: string; totalDebit: number };
type JournalData = { entries: Entry[]; accounts: Account[] };

export function AccountingView() {
  const { money } = useBusiness();
  const [data, setData] = useState<JournalData>({ entries: [], accounts: [] }); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [lines, setLines] = useState<Line[]>([{ account: "", debit: 0, credit: 0 }, { account: "", debit: 0, credit: 0 }]); const { notice, show } = useNotice();
  async function load() { setLoading(true); try { setData(await apiRequest<JournalData>("/api/journals")); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not load the journal.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const debits = lines.reduce((sum, line) => sum + Number(line.debit || 0), 0); const credits = lines.reduce((sum, line) => sum + Number(line.credit || 0), 0); const balanced = debits > 0 && Math.abs(debits - credits) < 0.009;
  function updateLine(index: number, patch: Partial<Line>) { setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { const payloadLines = lines.map((line) => { const [accountCode, ...nameParts] = line.account.split("|"); return { accountCode, accountName: nameParts.join("|"), debit: Number(line.debit || 0), credit: Number(line.credit || 0) }; }); await apiRequest("/api/journals", { method: "POST", body: JSON.stringify({ date: form.get("date"), memo: form.get("memo"), reference: form.get("reference"), lines: payloadLines }) }); show("Journal entry posted and locked."); setOpen(false); setLines([{ account: "", debit: 0, credit: 0 }, { account: "", debit: 0, credit: 0 }]); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not post journal.", "error"); } finally { setBusy(false); } }
  return <div className="page page-enter">
    <PageHeader eyebrow="GENERAL LEDGER" title="Accounting" description="Balanced entries, automatic POS posting and a traceable book of record." action={<AddButton onClick={() => setOpen(true)}>New journal</AddButton>} />
    {notice ? <Notice {...notice} /> : null}
    <section className="accounting-banner"><div><BookOpen /><span>POSTED ENTRIES</span><strong>{data.entries.length}</strong></div><i /><div><Scale /><span>CONTROL TOTAL</span><strong>{money.format(data.entries.reduce((sum, entry) => sum + entry.totalDebit, 0))}</strong></div><i /><div><CheckCircle2 /><span>BOOK STATUS</span><strong>Balanced</strong></div></section>
    <section className="panel resource-panel"><header className="panel-header"><div><span className="eyebrow">BOOK OF RECORD</span><h2>Recent journal entries</h2></div><span className="panel-note">NEWEST FIRST</span></header>
      {loading ? <LoadingPanel /> : data.entries.length ? <div className="data-list journal-list"><div className="data-list-head"><span>Entry</span><span>Date</span><span>Memo</span><span>Source</span><span>Total debit</span><span>Status</span></div>{data.entries.map((entry) => <div className="data-row" key={entry._id}><strong>{entry.entryNo}</strong><span>{new Date(entry.date).toLocaleDateString("en-SG")}</span><div><strong>{entry.memo}</strong><small>{entry.reference || "No reference"}</small></div><span>{entry.source}</span><strong>{money.format(entry.totalDebit)}</strong><StatusPill value={entry.status} /></div>)}</div> : <EmptyState title="No journal entries" detail="POS sales post automatically. You can also add a balanced manual journal." />}
    </section>
    <Modal open={open} onClose={() => setOpen(false)} title="Post journal entry" kicker="DOUBLE ENTRY"><form className="modal-form wide-form" onSubmit={submit}><div className="form-grid three"><label className="field"><span>Entry date</span><input name="date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label className="field span-two"><span>Memo</span><input name="memo" placeholder="What is this entry for?" required /></label></div><label className="field"><span>Reference · optional</span><input name="reference" placeholder="Supplier invoice or internal note" /></label><div className="journal-editor"><div className="journal-editor-head"><span>Account</span><span>Debit</span><span>Credit</span><span /></div>{lines.map((line, index) => <div className="journal-editor-line" key={index}><select value={line.account} onChange={(event) => updateLine(index, { account: event.target.value })} required><option value="">Choose account</option>{data.accounts.map((account) => <option key={account._id} value={`${account.code}|${account.name}`}>{account.code} · {account.name}</option>)}</select><input type="number" min="0" step="0.01" value={line.debit || ""} onChange={(event) => updateLine(index, { debit: Number(event.target.value), credit: Number(event.target.value) ? 0 : line.credit })} placeholder="0.00" /><input type="number" min="0" step="0.01" value={line.credit || ""} onChange={(event) => updateLine(index, { credit: Number(event.target.value), debit: Number(event.target.value) ? 0 : line.debit })} placeholder="0.00" /><button type="button" disabled={lines.length <= 2} onClick={() => setLines((current) => current.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div>)}<button type="button" className="add-line" onClick={() => setLines((current) => [...current, { account: "", debit: 0, credit: 0 }])}><Plus size={15} />Add line</button></div><div className={`balance-strip ${balanced ? "balanced" : ""}`}><span>Debit <b>{money.format(debits)}</b></span><span>Credit <b>{money.format(credits)}</b></span><strong>{balanced ? "BALANCED" : `DIFFERENCE ${money.format(Math.abs(debits - credits))}`}</strong></div><footer><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={!balanced || busy}>{busy ? "Posting…" : "Post journal"}</button></footer></form></Modal>
  </div>;
}
