"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, CircleDollarSign, PackagePlus, Search, SlidersHorizontal } from "lucide-react";
import { AddButton, apiRequest, EmptyState, LoadingPanel, Modal, money, Notice, PageHeader, useNotice } from "@/components/ui";
import type { ProductRecord } from "@/lib/types";

export function InventoryView() {
  const [products, setProducts] = useState<ProductRecord[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState("");
  const [addOpen, setAddOpen] = useState(false); const [adjusting, setAdjusting] = useState<ProductRecord | null>(null); const [busy, setBusy] = useState(false); const { notice, show } = useNotice();
  async function load() { setLoading(true); try { setProducts(await apiRequest<ProductRecord[]>("/api/products")); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not load inventory.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => products.filter((product) => `${product.name} ${product.sku} ${product.category}`.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const low = products.filter((product) => product.stock <= product.reorderLevel).length;
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await apiRequest("/api/products", { method: "POST", body: JSON.stringify(data) }); show("Product added to inventory."); setAddOpen(false); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not add product.", "error"); } finally { setBusy(false); } }
  async function adjust(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!adjusting) return; setBusy(true); const data = new FormData(event.currentTarget); try { await apiRequest("/api/products", { method: "PATCH", body: JSON.stringify({ id: adjusting._id, adjustment: data.get("adjustment"), reason: data.get("reason") }) }); show("Stock movement posted."); setAdjusting(null); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not adjust stock.", "error"); } finally { setBusy(false); } }
  return <div className="page page-enter">
    <PageHeader eyebrow="TEA STORE" title="Inventory" description="Track every tin, pouch and tool from shelf to sale." action={<AddButton onClick={() => setAddOpen(true)}>New product</AddButton>} />
    {notice ? <Notice {...notice} /> : null}
    <section className="mini-stat-row"><article><Boxes /><span>Units on hand</span><strong>{products.reduce((sum, product) => sum + product.stock, 0).toLocaleString()}</strong></article><article><CircleDollarSign /><span>Stock at cost</span><strong>{money.format(products.reduce((sum, product) => sum + product.cost * product.stock, 0))}</strong></article><article className={low ? "warn" : ""}><AlertTriangle /><span>At or below reorder</span><strong>{low}</strong></article></section>
    <section className="panel resource-panel"><div className="resource-toolbar"><label className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search product, category or SKU" /></label><span>{filtered.length} active SKUs</span></div>
      {loading ? <LoadingPanel /> : filtered.length ? <div className="data-list inventory-list"><div className="data-list-head"><span>Product</span><span>Category</span><span>On hand</span><span>Retail / cost</span><span>Stock value</span><span /></div>{filtered.map((product) => <div className="data-row" key={product._id}><div className="product-cell"><i>{product.name.toLowerCase().includes("hojicha") ? "焙" : "抹"}</i><div><strong>{product.name}</strong><small>{product.sku}</small></div></div><span>{product.category}</span><div><strong>{product.stock} {product.unit}</strong>{product.stock <= product.reorderLevel ? <small className="low-label">Reorder at {product.reorderLevel}</small> : <small>Healthy</small>}</div><div><strong>{money.format(product.price)}</strong><small>{money.format(product.cost)} cost</small></div><strong>{money.format(product.cost * product.stock)}</strong><button className="button button-quiet" onClick={() => setAdjusting(product)}><SlidersHorizontal size={15} />Adjust</button></div>)}</div> : <EmptyState title="The shelf is empty" detail="Add the first product to begin tracking stock." action={<AddButton onClick={() => setAddOpen(true)}>New product</AddButton>} />}
    </section>
    <Modal open={addOpen} onClose={() => setAddOpen(false)} title="New product" kicker="ADD TO SHELF"><form className="modal-form" onSubmit={add}><div className="form-grid two"><label className="field"><span>Product name</span><input name="name" required autoFocus /></label><label className="field"><span>SKU</span><input name="sku" pattern="[A-Za-z0-9._-]+" required /></label></div><div className="form-grid two"><label className="field"><span>Category</span><input name="category" placeholder="Matcha powder" required /></label><label className="field"><span>Unit</span><input name="unit" placeholder="tin" required /></label></div><div className="form-grid four"><label className="field"><span>Retail</span><input name="price" type="number" min="0" step="0.01" required /></label><label className="field"><span>Cost</span><input name="cost" type="number" min="0" step="0.01" required /></label><label className="field"><span>Opening stock</span><input name="stock" type="number" min="0" step="1" required /></label><label className="field"><span>Reorder at</span><input name="reorderLevel" type="number" min="0" step="1" required /></label></div><footer><button type="button" className="button button-secondary" onClick={() => setAddOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Saving…" : "Add product"}</button></footer></form></Modal>
    <Modal open={Boolean(adjusting)} onClose={() => setAdjusting(null)} title={`Adjust ${adjusting?.name || "stock"}`} kicker="STOCK MOVEMENT"><form className="modal-form" onSubmit={adjust}><p className="form-hint">Current balance: <strong>{adjusting?.stock} {adjusting?.unit}</strong>. Use a negative number to record wastage or a positive number for received stock.</p><label className="field"><span>Quantity change</span><input name="adjustment" type="number" step="1" placeholder="e.g. 12 or -2" required autoFocus /></label><label className="field"><span>Reason</span><input name="reason" placeholder="Supplier delivery, damaged tin…" required /></label><footer><button type="button" className="button button-secondary" onClick={() => setAdjusting(null)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Posting…" : "Post movement"}</button></footer></form></Modal>
  </div>;
}
