"use client";

import { FormEvent, useEffect, useState } from "react";
import { CircleDollarSign, Clock3, FilePlus2, FileText, Plus, Trash2 } from "lucide-react";
import { AddButton, apiRequest, EmptyState, LoadingPanel, Modal, money, Notice, PageHeader, shortDate, StatusPill, useNotice } from "@/components/ui";

type InvoiceItem = { description: string; quantity: number; unitPrice: number };
type Invoice = { _id: string; invoiceNo: string; customerName: string; customerEmail: string; dueDate: string; total: number; paidAmount: number; status: string; createdAt: string };

export function InvoicesView() {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [items, setItems] = useState<InvoiceItem[]>([{ description: "", quantity: 1, unitPrice: 0 }]); const { notice, show } = useNotice();
  async function load() { setLoading(true); try { setInvoices(await apiRequest<Invoice[]>("/api/invoices")); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not load invoices.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const outstanding = invoices.filter((invoice) => ["DRAFT", "SENT"].includes(invoice.status)).reduce((sum, invoice) => sum + invoice.total - invoice.paidAmount, 0);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await apiRequest("/api/invoices", { method: "POST", body: JSON.stringify({ customerName: data.get("customerName"), customerEmail: data.get("customerEmail"), dueDate: data.get("dueDate"), notes: data.get("notes"), items }) }); show("Invoice draft created."); setOpen(false); setItems([{ description: "", quantity: 1, unitPrice: 0 }]); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not create invoice.", "error"); } finally { setBusy(false); } }
  async function setStatus(id: string, status: string) { try { await apiRequest("/api/invoices", { method: "PATCH", body: JSON.stringify({ id, status }) }); show(`Invoice marked ${status.toLowerCase()}.`); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not update invoice.", "error"); } }
  const draftTotal = items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitPrice || 0), 0);
  function updateItem(index: number, patch: Partial<InvoiceItem>) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  return <div className="page page-enter">
    <PageHeader eyebrow="ACCOUNTS RECEIVABLE" title="Invoices" description="Create, issue and settle customer invoices without losing the paper trail." action={<AddButton onClick={() => setOpen(true)}>New invoice</AddButton>} />
    {notice ? <Notice {...notice} /> : null}
    <section className="mini-stat-row"><article><FileText /><span>Total invoices</span><strong>{invoices.length}</strong></article><article><Clock3 /><span>Outstanding</span><strong>{money.format(outstanding)}</strong></article><article><CircleDollarSign /><span>Paid</span><strong>{money.format(invoices.reduce((sum, invoice) => sum + invoice.paidAmount, 0))}</strong></article></section>
    <section className="panel resource-panel">{loading ? <LoadingPanel /> : invoices.length ? <div className="data-list invoice-list"><div className="data-list-head"><span>Invoice</span><span>Customer</span><span>Due</span><span>Amount</span><span>Status</span><span>Action</span></div>{invoices.map((invoice) => <div className="data-row" key={invoice._id}><div><strong>{invoice.invoiceNo}</strong><small>{shortDate.format(new Date(invoice.createdAt))}</small></div><div><strong>{invoice.customerName}</strong><small>{invoice.customerEmail || "No email"}</small></div><span>{shortDate.format(new Date(invoice.dueDate))}</span><strong>{money.format(invoice.total)}</strong><StatusPill value={invoice.status} /><select className="status-select" value={invoice.status} disabled={invoice.status === "VOID"} onChange={(event) => setStatus(invoice._id, event.target.value)}><option>DRAFT</option><option>SENT</option><option>PAID</option><option>VOID</option></select></div>)}</div> : <EmptyState title="No invoices drafted" detail="Create an invoice for wholesale, events or other account sales." action={<AddButton onClick={() => setOpen(true)}>New invoice</AddButton>} />}</section>
    <Modal open={open} onClose={() => setOpen(false)} title="Create invoice" kicker="NEW RECEIVABLE"><form className="modal-form wide-form" onSubmit={create}><div className="form-grid three"><label className="field"><span>Customer</span><input name="customerName" required autoFocus /></label><label className="field"><span>Email · optional</span><input name="customerEmail" type="email" /></label><label className="field"><span>Due date</span><input name="dueDate" type="date" defaultValue={new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10)} required /></label></div><div className="invoice-editor"><div className="invoice-editor-head"><span>Description</span><span>Qty</span><span>Unit price</span><span>Total</span><span /></div>{items.map((item, index) => <div className="invoice-editor-line" key={index}><input value={item.description} onChange={(event) => updateItem(index, { description: event.target.value })} placeholder="Product or service" required /><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(event) => updateItem(index, { quantity: Number(event.target.value) })} required /><input type="number" min="0" step="0.01" value={item.unitPrice || ""} onChange={(event) => updateItem(index, { unitPrice: Number(event.target.value) })} placeholder="0.00" required /><strong>{money.format(item.quantity * item.unitPrice)}</strong><button type="button" disabled={items.length === 1} onClick={() => setItems((current) => current.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div>)}<button type="button" className="add-line" onClick={() => setItems((current) => [...current, { description: "", quantity: 1, unitPrice: 0 }])}><Plus size={15} />Add item</button></div><label className="field"><span>Notes · optional</span><textarea name="notes" rows={3} /></label><div className="invoice-total"><span>Subtotal · workspace tax is added on save</span><strong>{money.format(draftTotal)}</strong></div><footer><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={!draftTotal || busy}><FilePlus2 size={16} />{busy ? "Creating…" : "Create draft"}</button></footer></form></Modal>
  </div>;
}
