"use client";

import { FormEvent, useEffect, useState } from "react";
import { BellRing, Building2, KeyRound, Save, ShieldCheck } from "lucide-react";
import { apiRequest, LoadingPanel, Notice, PageHeader, useNotice } from "@/components/ui";

type Settings = { businessName: string; registrationNo?: string; email?: string; phone?: string; address?: string; currency: "SGD"; taxName: string; taxRate: number; taxMode?: "EXCLUSIVE" | "INCLUSIVE"; pointsPerDollar: number; lowStockNotifications?: boolean; updatedAt?: string };

export function SettingsView() {
  const [settings, setSettings] = useState<Settings | null>(null); const [busy, setBusy] = useState(false); const { notice, show } = useNotice();
  useEffect(() => { apiRequest<Settings>("/api/settings").then(setSettings).catch((reason) => show(reason.message, "error")); }, [show]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { const updated = await apiRequest<Settings>("/api/settings", { method: "PATCH", body: JSON.stringify({ businessName: form.get("businessName"), registrationNo: form.get("registrationNo"), email: form.get("email"), phone: form.get("phone"), address: form.get("address"), currency: "SGD", taxName: form.get("taxName"), taxRate: form.get("taxRate"), taxMode: form.get("taxMode"), pointsPerDollar: form.get("pointsPerDollar"), lowStockNotifications: form.get("lowStockNotifications") === "on" }) }); setSettings(updated); show("Workspace settings saved."); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not save settings.", "error"); } finally { setBusy(false); } }
  async function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const target = event.currentTarget; const form = new FormData(target); try { await apiRequest("/api/profile", { method: "PATCH", body: JSON.stringify({ currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") }) }); target.reset(); show("Your password has been changed."); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not change password.", "error"); } }
  return <div className="page page-enter">
    <PageHeader eyebrow="WORKSPACE" title="Settings" description="Business identity, GST, membership rewards and your own sign-in security." />
    {notice ? <Notice {...notice} /> : null}
    {!settings ? <LoadingPanel /> : <div className="settings-grid"><form className="panel settings-form" onSubmit={save} key={settings.updatedAt || "settings"}><header className="settings-section-title"><Building2 /><div><h2>Business profile</h2><p>Shown on receipts, invoices and reports.</p></div></header><div className="form-grid two"><label className="field"><span>Business name</span><input name="businessName" defaultValue={settings.businessName} required /></label><label className="field"><span>Registration number</span><input name="registrationNo" defaultValue={settings.registrationNo} /></label></div><div className="form-grid two"><label className="field"><span>Business email</span><input name="email" type="email" defaultValue={settings.email} /></label><label className="field"><span>Phone</span><input name="phone" defaultValue={settings.phone} /></label></div><label className="field"><span>Address</span><textarea name="address" rows={3} defaultValue={settings.address} /></label><div className="settings-divider" /><header className="settings-section-title"><BellRing /><div><h2>Ledger rules</h2><p>Applied to new transactions.</p></div></header><div className="form-grid three"><label className="field"><span>Currency</span><input value="SGD" readOnly /></label><label className="field"><span>Tax name</span><input name="taxName" defaultValue={settings.taxName} required /></label><label className="field"><span>Tax rate %</span><input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue={settings.taxRate} required /></label></div><div className="form-grid two"><label className="field"><span>Retail price tax</span><select name="taxMode" defaultValue={settings.taxMode || "EXCLUSIVE"}><option value="EXCLUSIVE">Add tax at checkout</option><option value="INCLUSIVE">Tax included in shelf price</option></select></label><label className="field"><span>Member points per $1</span><input name="pointsPerDollar" type="number" min="0" max="100" step="0.1" defaultValue={settings.pointsPerDollar} required /></label></div><label className="check-row"><input name="lowStockNotifications" type="checkbox" defaultChecked={settings.lowStockNotifications !== false} /><span><strong>Low-stock attention markers</strong><small>Highlight products at or below their reorder level.</small></span></label><footer><button className="button button-primary" disabled={busy}><Save size={16} />{busy ? "Saving…" : "Save workspace"}</button></footer></form>
      <aside><form className="panel password-form" onSubmit={password}><header className="settings-section-title"><KeyRound /><div><h2>Change password</h2><p>Updates only your own account.</p></div></header><label className="field"><span>Current password</span><input name="currentPassword" type="password" autoComplete="current-password" required /></label><label className="field"><span>New password</span><input name="newPassword" type="password" minLength={12} autoComplete="new-password" required /></label><small>Use 12+ characters with upper and lowercase letters and a number.</small><button className="button button-secondary">Change password</button></form><div className="security-note"><ShieldCheck /><div><strong>Security baseline</strong><p>HTTP-only sessions, server-enforced roles, hashed passwords and an audit trail are active.</p></div></div></aside></div>}
  </div>;
}
