"use client";

import { FormEvent, useEffect, useState } from "react";
import { Activity, Copy, KeyRound, ShieldCheck, UserCog, UserPlus } from "lucide-react";
import { AddButton, apiRequest, dateTime, EmptyState, LoadingPanel, Modal, Notice, PageHeader, StatusPill, useNotice } from "@/components/ui";
import type { UserRole } from "@/lib/types";

type TeamUser = { _id: string; fullName: string; username: string; email: string; role: UserRole; active: boolean; createdAt: string; lastLoginAt?: string };
type Audit = { _id: string; actorName: string; action: string; entityType: string; createdAt: string };
type TeamData = { users: TeamUser[]; audit: Audit[] };

function generatedPassword() {
  const bytes = new Uint32Array(3); crypto.getRandomValues(bytes);
  return `Matcha!${bytes[0].toString(36)}-${bytes[1].toString(36).toUpperCase()}-${(bytes[2] % 1000).toString().padStart(3, "0")}`;
}

export function TeamView({ actorRole }: { actorRole: UserRole }) {
  const [data, setData] = useState<TeamData>({ users: [], audit: [] }); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [password, setPassword] = useState(""); const [issued, setIssued] = useState<{ username: string; password: string } | null>(null); const { notice, show } = useNotice();
  const canWrite = ["OWNER", "ADMIN"].includes(actorRole);
  async function load() { setLoading(true); try { setData(await apiRequest<TeamData>("/api/users")); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not load access controls.", "error"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function openCreate() { setPassword(generatedPassword()); setOpen(true); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const username = String(form.get("username")); try { await apiRequest("/api/users", { method: "POST", body: JSON.stringify({ fullName: form.get("fullName"), username, email: form.get("email"), role: form.get("role"), password }) }); setOpen(false); setIssued({ username, password }); show("Staff account generated and audit logged."); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not create the account.", "error"); } finally { setBusy(false); } }
  async function update(user: TeamUser, patch: { role?: UserRole; active?: boolean }) { try { await apiRequest("/api/users", { method: "PATCH", body: JSON.stringify({ id: user._id, ...patch }) }); show("Access updated."); await load(); } catch (reason) { show(reason instanceof Error ? reason.message : "Could not update access.", "error"); } }
  const manageable = (user: TeamUser) => canWrite && user.role !== "OWNER" && !(actorRole === "ADMIN" && user.role === "ADMIN");
  return <div className="page page-enter">
    <PageHeader eyebrow="OWNER CONTROL" title="Team & access" description="Generate staff accounts, assign the smallest useful role and keep every change traceable." action={canWrite ? <AddButton onClick={openCreate}>Generate account</AddButton> : undefined} />
    {notice ? <Notice {...notice} /> : null}
    <section className="access-callout"><ShieldCheck /><div><strong>Owner is the highest authority</strong><p>Only the Owner can create or manage Admin accounts. Passwords are hashed before storage and never displayed again after this screen.</p></div><span>RBAC ACTIVE</span></section>
    <section className="team-layout"><article className="panel resource-panel"><header className="panel-header"><div><span className="eyebrow">STAFF DIRECTORY</span><h2>{data.users.length} accounts</h2></div><UserCog /></header>{loading ? <LoadingPanel /> : data.users.length ? <div className="team-list">{data.users.map((user) => <div className="team-row" key={user._id}><div className="member-avatar">{user.fullName.split(/\s+/).map((part) => part[0]).join("").slice(0, 2)}</div><div><strong>{user.fullName}</strong><span>@{user.username} · {user.email || "No email"}</span></div><StatusPill value={user.active ? "ACTIVE" : "DISABLED"} />{manageable(user) ? <select value={user.role} onChange={(event) => update(user, { role: event.target.value as UserRole })}><option value="ADMIN" disabled={actorRole !== "OWNER"}>Admin</option><option value="MANAGER">Manager</option><option value="ACCOUNTANT">Accountant</option><option value="CASHIER">Cashier</option></select> : <span className="role-label">{user.role}</span>}{manageable(user) ? <button className={`button ${user.active ? "button-quiet danger" : "button-secondary"}`} onClick={() => update(user, { active: !user.active })}>{user.active ? "Disable" : "Enable"}</button> : <span />}</div>)}</div> : <EmptyState title="No staff accounts" detail="Generate the first account for a manager, accountant or cashier." />}</article>
      <aside className="panel audit-panel"><header className="panel-header"><div><span className="eyebrow">SECURITY LOG</span><h2>Recent activity</h2></div><Activity /></header><div className="audit-list">{data.audit.map((item) => <div key={item._id}><i /><div><strong>{item.action.replaceAll(".", " · ")}</strong><span>{item.actorName} · {item.entityType}</span></div><time>{dateTime.format(new Date(item.createdAt))}</time></div>)}</div></aside>
    </section>
    <Modal open={open} onClose={() => setOpen(false)} title="Generate staff account" kicker="OWNER CONTROL"><form className="modal-form" onSubmit={create}><div className="form-grid two"><label className="field"><span>Full name</span><input name="fullName" required autoFocus /></label><label className="field"><span>Username</span><input name="username" pattern="[A-Za-z0-9._-]+" required /></label></div><div className="form-grid two"><label className="field"><span>Email · optional</span><input name="email" type="email" /></label><label className="field"><span>Role</span><select name="role" defaultValue="CASHIER"><option value="ADMIN" disabled={actorRole !== "OWNER"}>Admin</option><option value="MANAGER">Manager</option><option value="ACCOUNTANT">Accountant</option><option value="CASHIER">Cashier</option></select></label></div><label className="field"><span>Temporary password</span><div className="generated-password"><KeyRound size={16} /><input value={password} onChange={(event) => setPassword(event.target.value)} required minLength={12} /><button type="button" onClick={() => setPassword(generatedPassword())}>Regenerate</button></div></label><p className="form-hint">Share this password through a secure channel. The staff member can change it in Workspace settings.</p><footer><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}><UserPlus size={16} />{busy ? "Generating…" : "Generate account"}</button></footer></form></Modal>
    <Modal open={Boolean(issued)} onClose={() => setIssued(null)} title="Account ready" kicker="COPY ONCE">{issued ? <div className="credentials-card"><p>These credentials will not be shown again.</p><label><span>Username</span><strong>{issued.username}</strong></label><label><span>Temporary password</span><strong>{issued.password}</strong></label><button className="button button-primary" onClick={async () => { await navigator.clipboard.writeText(`Username: ${issued.username}\nTemporary password: ${issued.password}`); show("Credentials copied."); }}><Copy size={16} />Copy credentials</button></div> : null}</Modal>
  </div>;
}
