// Generated from IANA tzdb 2025b and Unicode CLDR 48; see docs/regional-settings.md.
// Unicode data licence: docs/UNICODE-LICENSE.txt. Regenerate with scripts/country-data.mjs.
export const REGION_DATA = [
  {"code":"AF","name":"Afghanistan","currencies":["AFN"],"locale":"fa-AF","timeZones":["Asia/Kabul"]},
  {"code":"AX","name":"Åland Islands","currencies":["EUR"],"locale":"sv-AX","timeZones":["Europe/Mariehamn"]},
  {"code":"AL","name":"Albania","currencies":["ALL"],"locale":"sq-AL","timeZones":["Europe/Tirane"]},
  {"code":"DZ","name":"Algeria","currencies":["DZD"],"locale":"ar-DZ","timeZones":["Africa/Algiers"]},
  {"code":"AS","name":"American Samoa","currencies":["USD"],"locale":"sm-AS","timeZones":["Pacific/Pago_Pago"]},
  {"code":"AD","name":"Andorra","currencies":["EUR"],"locale":"ca-AD","timeZones":["Europe/Andorra"]},
  {"code":"AO","name":"Angola","currencies":["AOA"],"locale":"pt-AO","timeZones":["Africa/Luanda"]},
  {"code":"AI","name":"Anguilla","currencies":["XCD"],"locale":"en-AI","timeZones":["America/Anguilla"]},
  {"code":"AQ","name":"Antarctica","currencies":[],"locale":"en-AQ","timeZones":["Antarctica/McMurdo","Antarctica/Casey","Antarctica/Davis","Antarctica/DumontDUrville","Antarctica/Mawson","Antarctica/Palmer","Antarctica/Rothera","Antarctica/Syowa","Antarctica/Troll","Antarctica/Vostok"]},
  {"code":"AG","name":"Antigua & Barbuda","currencies":["XCD"],"locale":"en-AG","timeZones":["America/Antigua"]},
  {"code":"AR","name":"Argentina","currencies":["ARS"],"locale":"es-AR","timeZones":["America/Argentina/Buenos_Aires","America/Argentina/Cordoba","America/Argentina/Salta","America/Argentina/Jujuy","America/Argentina/Tucuman","America/Argentina/Catamarca","America/Argentina/La_Rioja","America/Argentina/San_Juan","America/Argentina/Mendoza","America/Argentina/San_Luis","America/Argentina/Rio_Gallegos","America/Argentina/Ushuaia"]},
  {"code":"AM","name":"Armenia","currencies":["AMD"],"locale":"hy-AM","timeZones":["Asia/Yerevan"]},
  {"code":"AW","name":"Aruba","currencies":["AWG"],"locale":"nl-AW","timeZones":["America/Aruba"]},
  {"code":"AU","name":"Australia","currencies":["AUD"],"locale":"en-AU","timeZones":["Australia/Lord_Howe","Antarctica/Macquarie","Australia/Hobart","Australia/Melbourne","Australia/Sydney","Australia/Broken_Hill","Australia/Brisbane","Australia/Lindeman","Australia/Adelaide","Australia/Darwin","Australia/Perth","Australia/Eucla"]},
  {"code":"AT","name":"Austria","currencies":["EUR"],"locale":"de-AT","timeZones":["Europe/Vienna"]},
  {"code":"AZ","name":"Azerbaijan","currencies":["AZN"],"locale":"az-AZ","timeZones":["Asia/Baku"]},
  {"code":"BS","name":"Bahamas","currencies":["BSD"],"locale":"en-BS","timeZones":["America/Nassau"]},
  {"code":"BH","name":"Bahrain","currencies":["BHD"],"locale":"ar-BH","timeZones":["Asia/Bahrain"]},
  {"code":"BD","name":"Bangladesh","currencies":["BDT"],"locale":"bn-BD","timeZones":["Asia/Dhaka"]},
  {"code":"BB","name":"Barbados","currencies":["BBD"],"locale":"en-BB","timeZones":["America/Barbados"]},
  {"code":"BY","name":"Belarus","currencies":["BYN"],"locale":"ru-BY","timeZones":["Europe/Minsk"]},
  {"code":"BE","name":"Belgium","currencies":["EUR"],"locale":"nl-BE","timeZones":["Europe/Brussels"]},
  {"code":"BZ","name":"Belize","currencies":["BZD"],"locale":"en-BZ","timeZones":["America/Belize"]},
  {"code":"BJ","name":"Benin","currencies":["XOF"],"locale":"fr-BJ","timeZones":["Africa/Porto-Novo"]},
  {"code":"BM","name":"Bermuda","currencies":["BMD"],"locale":"en-BM","timeZones":["Atlantic/Bermuda"]},
  {"code":"BT","name":"Bhutan","currencies":["BTN","INR"],"locale":"dz-BT","timeZones":["Asia/Thimphu"]},
  {"code":"BO","name":"Bolivia","currencies":["BOB"],"locale":"es-BO","timeZones":["America/La_Paz"]},
  {"code":"BA","name":"Bosnia & Herzegovina","currencies":["BAM"],"locale":"bs-BA","timeZones":["Europe/Sarajevo"]},
  {"code":"BW","name":"Botswana","currencies":["BWP"],"locale":"en-BW","timeZones":["Africa/Gaborone"]},
  {"code":"BV","name":"Bouvet Island","currencies":["NOK"],"locale":"no-BV","timeZones":[]},
  {"code":"BR","name":"Brazil","currencies":["BRL"],"locale":"pt-BR","timeZones":["America/Noronha","America/Belem","America/Fortaleza","America/Recife","America/Araguaina","America/Maceio","America/Bahia","America/Sao_Paulo","America/Campo_Grande","America/Cuiaba","America/Santarem","America/Porto_Velho","America/Boa_Vista","America/Manaus","America/Eirunepe","America/Rio_Branco"]},
  {"code":"IO","name":"British Indian Ocean Territory","currencies":["USD"],"locale":"en-IO","timeZones":["Indian/Chagos"]},
  {"code":"VG","name":"British Virgin Islands","currencies":["USD"],"locale":"en-VG","timeZones":["America/Tortola"]},
  {"code":"BN","name":"Brunei","currencies":["BND"],"locale":"ms-BN","timeZones":["Asia/Brunei"]},
  {"code":"BG","name":"Bulgaria","currencies":["EUR"],"locale":"bg-BG","timeZones":["Europe/Sofia"]},
  {"code":"BF","name":"Burkina Faso","currencies":["XOF"],"locale":"fr-BF","timeZones":["Africa/Ouagadougou"]},
  {"code":"BI","name":"Burundi","currencies":["BIF"],"locale":"rn-BI","timeZones":["Africa/Bujumbura"]},
  {"code":"KH","name":"Cambodia","currencies":["KHR"],"locale":"km-KH","timeZones":["Asia/Phnom_Penh"]},
  {"code":"CM","name":"Cameroon","currencies":["XAF"],"locale":"fr-CM","timeZones":["Africa/Douala"]},
  {"code":"CA","name":"Canada","currencies":["CAD"],"locale":"en-CA","timeZones":["America/St_Johns","America/Halifax","America/Glace_Bay","America/Moncton","America/Goose_Bay","America/Blanc-Sablon","America/Toronto","America/Iqaluit","America/Atikokan","America/Winnipeg","America/Resolute","America/Rankin_Inlet","America/Regina","America/Swift_Current","America/Edmonton","America/Cambridge_Bay","America/Inuvik","America/Creston","America/Dawson_Creek","America/Fort_Nelson","America/Whitehorse","America/Dawson","America/Vancouver"]},
  {"code":"CV","name":"Cape Verde","currencies":["CVE"],"locale":"pt-CV","timeZones":["Atlantic/Cape_Verde"]},
  {"code":"BQ","name":"Caribbean Netherlands","currencies":["USD"],"locale":"pap-BQ","timeZones":["America/Kralendijk"]},
  {"code":"KY","name":"Cayman Islands","currencies":["KYD"],"locale":"en-KY","timeZones":["America/Cayman"]},
  {"code":"CF","name":"Central African Republic","currencies":["XAF"],"locale":"sg-CF","timeZones":["Africa/Bangui"]},
  {"code":"TD","name":"Chad","currencies":["XAF"],"locale":"ar-TD","timeZones":["Africa/Ndjamena"]},
  {"code":"CL","name":"Chile","currencies":["CLP"],"locale":"es-CL","timeZones":["America/Santiago","America/Coyhaique","America/Punta_Arenas","Pacific/Easter"]},
  {"code":"CN","name":"China","currencies":["CNY"],"locale":"zh-CN","timeZones":["Asia/Shanghai","Asia/Urumqi"]},
  {"code":"CX","name":"Christmas Island","currencies":["AUD"],"locale":"en-CX","timeZones":["Indian/Christmas"]},
  {"code":"CC","name":"Cocos (Keeling) Islands","currencies":["AUD"],"locale":"ms-CC","timeZones":["Indian/Cocos"]},
  {"code":"CO","name":"Colombia","currencies":["COP"],"locale":"es-CO","timeZones":["America/Bogota"]},
  {"code":"KM","name":"Comoros","currencies":["KMF"],"locale":"ar-KM","timeZones":["Indian/Comoro"]},
  {"code":"CG","name":"Congo - Brazzaville","currencies":["XAF"],"locale":"fr-CG","timeZones":["Africa/Brazzaville"]},
  {"code":"CD","name":"Congo - Kinshasa","currencies":["CDF"],"locale":"fr-CD","timeZones":["Africa/Kinshasa","Africa/Lubumbashi"]},
  {"code":"CK","name":"Cook Islands","currencies":["NZD"],"locale":"en-CK","timeZones":["Pacific/Rarotonga"]},
  {"code":"CR","name":"Costa Rica","currencies":["CRC"],"locale":"es-CR","timeZones":["America/Costa_Rica"]},
  {"code":"CI","name":"Côte d’Ivoire","currencies":["XOF"],"locale":"fr-CI","timeZones":["Africa/Abidjan"]},
  {"code":"HR","name":"Croatia","currencies":["EUR"],"locale":"hr-HR","timeZones":["Europe/Zagreb"]},
  {"code":"CU","name":"Cuba","currencies":["CUP"],"locale":"es-CU","timeZones":["America/Havana"]},
  {"code":"CW","name":"Curaçao","currencies":["XCG"],"locale":"pap-CW","timeZones":["America/Curacao"]},
  {"code":"CY","name":"Cyprus","currencies":["EUR"],"locale":"el-CY","timeZones":["Asia/Nicosia","Asia/Famagusta"]},
  {"code":"CZ","name":"Czechia","currencies":["CZK"],"locale":"cs-CZ","timeZones":["Europe/Prague"]},
  {"code":"DK","name":"Denmark","currencies":["DKK"],"locale":"da-DK","timeZones":["Europe/Copenhagen"]},
  {"code":"DJ","name":"Djibouti","currencies":["DJF"],"locale":"fr-DJ","timeZones":["Africa/Djibouti"]},
  {"code":"DM","name":"Dominica","currencies":["XCD"],"locale":"en-DM","timeZones":["America/Dominica"]},
  {"code":"DO","name":"Dominican Republic","currencies":["DOP"],"locale":"es-DO","timeZones":["America/Santo_Domingo"]},
  {"code":"EC","name":"Ecuador","currencies":["USD"],"locale":"es-EC","timeZones":["America/Guayaquil","Pacific/Galapagos"]},
  {"code":"EG","name":"Egypt","currencies":["EGP"],"locale":"ar-EG","timeZones":["Africa/Cairo"]},
  {"code":"SV","name":"El Salvador","currencies":["USD"],"locale":"es-SV","timeZones":["America/El_Salvador"]},
  {"code":"GQ","name":"Equatorial Guinea","currencies":["XAF"],"locale":"es-GQ","timeZones":["Africa/Malabo"]},
  {"code":"ER","name":"Eritrea","currencies":["ERN"],"locale":"ti-ER","timeZones":["Africa/Asmara"]},
  {"code":"EE","name":"Estonia","currencies":["EUR"],"locale":"et-EE","timeZones":["Europe/Tallinn"]},
  {"code":"SZ","name":"Eswatini","currencies":["SZL"],"locale":"en-SZ","timeZones":["Africa/Mbabane"]},
  {"code":"ET","name":"Ethiopia","currencies":["ETB"],"locale":"am-ET","timeZones":["Africa/Addis_Ababa"]},
  {"code":"FK","name":"Falkland Islands","currencies":["FKP"],"locale":"en-FK","timeZones":["Atlantic/Stanley"]},
  {"code":"FO","name":"Faroe Islands","currencies":["DKK"],"locale":"fo-FO","timeZones":["Atlantic/Faroe"]},
  {"code":"FJ","name":"Fiji","currencies":["FJD"],"locale":"en-FJ","timeZones":["Pacific/Fiji"]},
  {"code":"FI","name":"Finland","currencies":["EUR"],"locale":"fi-FI","timeZones":["Europe/Helsinki"]},
  {"code":"FR","name":"France","currencies":["EUR"],"locale":"fr-FR","timeZones":["Europe/Paris"]},
  {"code":"GF","name":"French Guiana","currencies":["EUR"],"locale":"fr-GF","timeZones":["America/Cayenne"]},
  {"code":"PF","name":"French Polynesia","currencies":["XPF"],"locale":"fr-PF","timeZones":["Pacific/Tahiti","Pacific/Marquesas","Pacific/Gambier"]},
  {"code":"TF","name":"French Southern Territories","currencies":["EUR"],"locale":"fr-TF","timeZones":["Indian/Kerguelen"]},
  {"code":"GA","name":"Gabon","currencies":["XAF"],"locale":"fr-GA","timeZones":["Africa/Libreville"]},
  {"code":"GM","name":"Gambia","currencies":["GMD"],"locale":"en-GM","timeZones":["Africa/Banjul"]},
  {"code":"GE","name":"Georgia","currencies":["GEL"],"locale":"ka-GE","timeZones":["Asia/Tbilisi"]},
  {"code":"DE","name":"Germany","currencies":["EUR"],"locale":"de-DE","timeZones":["Europe/Berlin","Europe/Busingen"]},
  {"code":"GH","name":"Ghana","currencies":["GHS"],"locale":"ak-GH","timeZones":["Africa/Accra"]},
  {"code":"GI","name":"Gibraltar","currencies":["GIP"],"locale":"en-GI","timeZones":["Europe/Gibraltar"]},
  {"code":"GR","name":"Greece","currencies":["EUR"],"locale":"el-GR","timeZones":["Europe/Athens"]},
  {"code":"GL","name":"Greenland","currencies":["DKK"],"locale":"kl-GL","timeZones":["America/Nuuk","America/Danmarkshavn","America/Scoresbysund","America/Thule"]},
  {"code":"GD","name":"Grenada","currencies":["XCD"],"locale":"en-GD","timeZones":["America/Grenada"]},
  {"code":"GP","name":"Guadeloupe","currencies":["EUR"],"locale":"fr-GP","timeZones":["America/Guadeloupe"]},
  {"code":"GU","name":"Guam","currencies":["USD"],"locale":"en-GU","timeZones":["Pacific/Guam"]},
  {"code":"GT","name":"Guatemala","currencies":["GTQ"],"locale":"es-GT","timeZones":["America/Guatemala"]},
  {"code":"GG","name":"Guernsey","currencies":["GBP"],"locale":"en-GG","timeZones":["Europe/Guernsey"]},
  {"code":"GN","name":"Guinea","currencies":["GNF"],"locale":"fr-GN","timeZones":["Africa/Conakry"]},
  {"code":"GW","name":"Guinea-Bissau","currencies":["XOF"],"locale":"pt-GW","timeZones":["Africa/Bissau"]},
  {"code":"GY","name":"Guyana","currencies":["GYD"],"locale":"en-GY","timeZones":["America/Guyana"]},
  {"code":"HT","name":"Haiti","currencies":["HTG","USD"],"locale":"ht-HT","timeZones":["America/Port-au-Prince"]},
  {"code":"HM","name":"Heard & McDonald Islands","currencies":["AUD"],"locale":"en-HM","timeZones":[]},
  {"code":"HN","name":"Honduras","currencies":["HNL"],"locale":"es-HN","timeZones":["America/Tegucigalpa"]},
  {"code":"HK","name":"Hong Kong SAR China","currencies":["HKD"],"locale":"zh-HK","timeZones":["Asia/Hong_Kong"]},
  {"code":"HU","name":"Hungary","currencies":["HUF"],"locale":"hu-HU","timeZones":["Europe/Budapest"]},
  {"code":"IS","name":"Iceland","currencies":["ISK"],"locale":"is-IS","timeZones":["Atlantic/Reykjavik"]},
  {"code":"IN","name":"India","currencies":["INR"],"locale":"hi-IN","timeZones":["Asia/Kolkata"]},
  {"code":"ID","name":"Indonesia","currencies":["IDR"],"locale":"id-ID","timeZones":["Asia/Jakarta","Asia/Pontianak","Asia/Makassar","Asia/Jayapura"]},
  {"code":"IR","name":"Iran","currencies":["IRR"],"locale":"fa-IR","timeZones":["Asia/Tehran"]},
  {"code":"IQ","name":"Iraq","currencies":["IQD"],"locale":"ar-IQ","timeZones":["Asia/Baghdad"]},
  {"code":"IE","name":"Ireland","currencies":["EUR"],"locale":"en-IE","timeZones":["Europe/Dublin"]},
  {"code":"IM","name":"Isle of Man","currencies":["GBP"],"locale":"en-IM","timeZones":["Europe/Isle_of_Man"]},
  {"code":"IL","name":"Israel","currencies":["ILS"],"locale":"he-IL","timeZones":["Asia/Jerusalem"]},
  {"code":"IT","name":"Italy","currencies":["EUR"],"locale":"it-IT","timeZones":["Europe/Rome"]},
  {"code":"JM","name":"Jamaica","currencies":["JMD"],"locale":"en-JM","timeZones":["America/Jamaica"]},
  {"code":"JP","name":"Japan","currencies":["JPY"],"locale":"ja-JP","timeZones":["Asia/Tokyo"]},
  {"code":"JE","name":"Jersey","currencies":["GBP"],"locale":"en-JE","timeZones":["Europe/Jersey"]},
  {"code":"JO","name":"Jordan","currencies":["JOD"],"locale":"ar-JO","timeZones":["Asia/Amman"]},
  {"code":"KZ","name":"Kazakhstan","currencies":["KZT"],"locale":"ru-KZ","timeZones":["Asia/Almaty","Asia/Qyzylorda","Asia/Qostanay","Asia/Aqtobe","Asia/Aqtau","Asia/Atyrau","Asia/Oral"]},
  {"code":"KE","name":"Kenya","currencies":["KES"],"locale":"sw-KE","timeZones":["Africa/Nairobi"]},
  {"code":"KI","name":"Kiribati","currencies":["AUD"],"locale":"en-KI","timeZones":["Pacific/Tarawa","Pacific/Kanton","Pacific/Kiritimati"]},
  {"code":"KW","name":"Kuwait","currencies":["KWD"],"locale":"ar-KW","timeZones":["Asia/Kuwait"]},
  {"code":"KG","name":"Kyrgyzstan","currencies":["KGS"],"locale":"ky-KG","timeZones":["Asia/Bishkek"]},
  {"code":"LA","name":"Laos","currencies":["LAK"],"locale":"lo-LA","timeZones":["Asia/Vientiane"]},
  {"code":"LV","name":"Latvia","currencies":["EUR"],"locale":"lv-LV","timeZones":["Europe/Riga"]},
  {"code":"LB","name":"Lebanon","currencies":["LBP"],"locale":"ar-LB","timeZones":["Asia/Beirut"]},
  {"code":"LS","name":"Lesotho","currencies":["ZAR","LSL"],"locale":"st-LS","timeZones":["Africa/Maseru"]},
  {"code":"LR","name":"Liberia","currencies":["LRD"],"locale":"en-LR","timeZones":["Africa/Monrovia"]},
  {"code":"LY","name":"Libya","currencies":["LYD"],"locale":"ar-LY","timeZones":["Africa/Tripoli"]},
  {"code":"LI","name":"Liechtenstein","currencies":["CHF"],"locale":"de-LI","timeZones":["Europe/Vaduz"]},
  {"code":"LT","name":"Lithuania","currencies":["EUR"],"locale":"lt-LT","timeZones":["Europe/Vilnius"]},
  {"code":"LU","name":"Luxembourg","currencies":["EUR"],"locale":"fr-LU","timeZones":["Europe/Luxembourg"]},
  {"code":"MO","name":"Macao SAR China","currencies":["MOP"],"locale":"zh-MO","timeZones":["Asia/Macau"]},
  {"code":"MG","name":"Madagascar","currencies":["MGA"],"locale":"mg-MG","timeZones":["Indian/Antananarivo"]},
  {"code":"MW","name":"Malawi","currencies":["MWK"],"locale":"en-MW","timeZones":["Africa/Blantyre"]},
  {"code":"MY","name":"Malaysia","currencies":["MYR"],"locale":"ms-MY","timeZones":["Asia/Kuala_Lumpur","Asia/Kuching"]},
  {"code":"MV","name":"Maldives","currencies":["MVR"],"locale":"dv-MV","timeZones":["Indian/Maldives"]},
  {"code":"ML","name":"Mali","currencies":["XOF"],"locale":"bm-ML","timeZones":["Africa/Bamako"]},
  {"code":"MT","name":"Malta","currencies":["EUR"],"locale":"mt-MT","timeZones":["Europe/Malta"]},
  {"code":"MH","name":"Marshall Islands","currencies":["USD"],"locale":"en-MH","timeZones":["Pacific/Majuro","Pacific/Kwajalein"]},
  {"code":"MQ","name":"Martinique","currencies":["EUR"],"locale":"fr-MQ","timeZones":["America/Martinique"]},
  {"code":"MR","name":"Mauritania","currencies":["MRU"],"locale":"ar-MR","timeZones":["Africa/Nouakchott"]},
  {"code":"MU","name":"Mauritius","currencies":["MUR"],"locale":"fr-MU","timeZones":["Indian/Mauritius"]},
  {"code":"YT","name":"Mayotte","currencies":["EUR"],"locale":"fr-YT","timeZones":["Indian/Mayotte"]},
  {"code":"MX","name":"Mexico","currencies":["MXN"],"locale":"es-MX","timeZones":["America/Mexico_City","America/Cancun","America/Merida","America/Monterrey","America/Matamoros","America/Chihuahua","America/Ciudad_Juarez","America/Ojinaga","America/Mazatlan","America/Bahia_Banderas","America/Hermosillo","America/Tijuana"]},
  {"code":"FM","name":"Micronesia","currencies":["USD"],"locale":"en-FM","timeZones":["Pacific/Chuuk","Pacific/Pohnpei","Pacific/Kosrae"]},
  {"code":"MD","name":"Moldova","currencies":["MDL"],"locale":"ro-MD","timeZones":["Europe/Chisinau"]},
  {"code":"MC","name":"Monaco","currencies":["EUR"],"locale":"fr-MC","timeZones":["Europe/Monaco"]},
  {"code":"MN","name":"Mongolia","currencies":["MNT"],"locale":"mn-MN","timeZones":["Asia/Ulaanbaatar","Asia/Hovd"]},
  {"code":"ME","name":"Montenegro","currencies":["EUR"],"locale":"sr-ME","timeZones":["Europe/Podgorica"]},
  {"code":"MS","name":"Montserrat","currencies":["XCD"],"locale":"en-MS","timeZones":["America/Montserrat"]},
  {"code":"MA","name":"Morocco","currencies":["MAD"],"locale":"ar-MA","timeZones":["Africa/Casablanca"]},
  {"code":"MZ","name":"Mozambique","currencies":["MZN"],"locale":"pt-MZ","timeZones":["Africa/Maputo"]},
  {"code":"MM","name":"Myanmar (Burma)","currencies":["MMK"],"locale":"my-MM","timeZones":["Asia/Yangon"]},
  {"code":"NA","name":"Namibia","currencies":["NAD","ZAR"],"locale":"af-NA","timeZones":["Africa/Windhoek"]},
  {"code":"NR","name":"Nauru","currencies":["AUD"],"locale":"en-NR","timeZones":["Pacific/Nauru"]},
  {"code":"NP","name":"Nepal","currencies":["NPR"],"locale":"ne-NP","timeZones":["Asia/Kathmandu"]},
  {"code":"NL","name":"Netherlands","currencies":["EUR"],"locale":"nl-NL","timeZones":["Europe/Amsterdam"]},
  {"code":"NC","name":"New Caledonia","currencies":["XPF"],"locale":"fr-NC","timeZones":["Pacific/Noumea"]},
  {"code":"NZ","name":"New Zealand","currencies":["NZD"],"locale":"en-NZ","timeZones":["Pacific/Auckland","Pacific/Chatham"]},
  {"code":"NI","name":"Nicaragua","currencies":["NIO"],"locale":"es-NI","timeZones":["America/Managua"]},
  {"code":"NE","name":"Niger","currencies":["XOF"],"locale":"ha-NE","timeZones":["Africa/Niamey"]},
  {"code":"NG","name":"Nigeria","currencies":["NGN"],"locale":"en-NG","timeZones":["Africa/Lagos"]},
  {"code":"NU","name":"Niue","currencies":["NZD"],"locale":"en-NU","timeZones":["Pacific/Niue"]},
  {"code":"NF","name":"Norfolk Island","currencies":["AUD"],"locale":"en-NF","timeZones":["Pacific/Norfolk"]},
  {"code":"KP","name":"North Korea","currencies":["KPW"],"locale":"ko-KP","timeZones":["Asia/Pyongyang"]},
  {"code":"MK","name":"North Macedonia","currencies":["MKD"],"locale":"mk-MK","timeZones":["Europe/Skopje"]},
  {"code":"MP","name":"Northern Mariana Islands","currencies":["USD"],"locale":"en-MP","timeZones":["Pacific/Saipan"]},
  {"code":"NO","name":"Norway","currencies":["NOK"],"locale":"nb-NO","timeZones":["Europe/Oslo"]},
  {"code":"OM","name":"Oman","currencies":["OMR"],"locale":"ar-OM","timeZones":["Asia/Muscat"]},
  {"code":"PK","name":"Pakistan","currencies":["PKR"],"locale":"ur-PK","timeZones":["Asia/Karachi"]},
  {"code":"PW","name":"Palau","currencies":["USD"],"locale":"pau-PW","timeZones":["Pacific/Palau"]},
  {"code":"PS","name":"Palestinian Territories","currencies":["ILS","JOD"],"locale":"ar-PS","timeZones":["Asia/Gaza","Asia/Hebron"]},
  {"code":"PA","name":"Panama","currencies":["PAB","USD"],"locale":"es-PA","timeZones":["America/Panama"]},
  {"code":"PG","name":"Papua New Guinea","currencies":["PGK"],"locale":"tpi-PG","timeZones":["Pacific/Port_Moresby","Pacific/Bougainville"]},
  {"code":"PY","name":"Paraguay","currencies":["PYG"],"locale":"gn-PY","timeZones":["America/Asuncion"]},
  {"code":"PE","name":"Peru","currencies":["PEN"],"locale":"es-PE","timeZones":["America/Lima"]},
  {"code":"PH","name":"Philippines","currencies":["PHP"],"locale":"fil-PH","timeZones":["Asia/Manila"]},
  {"code":"PN","name":"Pitcairn Islands","currencies":["NZD"],"locale":"en-PN","timeZones":["Pacific/Pitcairn"]},
  {"code":"PL","name":"Poland","currencies":["PLN"],"locale":"pl-PL","timeZones":["Europe/Warsaw"]},
  {"code":"PT","name":"Portugal","currencies":["EUR"],"locale":"pt-PT","timeZones":["Europe/Lisbon","Atlantic/Madeira","Atlantic/Azores"]},
  {"code":"PR","name":"Puerto Rico","currencies":["USD"],"locale":"es-PR","timeZones":["America/Puerto_Rico"]},
  {"code":"QA","name":"Qatar","currencies":["QAR"],"locale":"ar-QA","timeZones":["Asia/Qatar"]},
  {"code":"RE","name":"Réunion","currencies":["EUR"],"locale":"fr-RE","timeZones":["Indian/Reunion"]},
  {"code":"RO","name":"Romania","currencies":["RON"],"locale":"ro-RO","timeZones":["Europe/Bucharest"]},
  {"code":"RU","name":"Russia","currencies":["RUB"],"locale":"ru-RU","timeZones":["Europe/Kaliningrad","Europe/Moscow","Europe/Kirov","Europe/Volgograd","Europe/Astrakhan","Europe/Saratov","Europe/Ulyanovsk","Europe/Samara","Asia/Yekaterinburg","Asia/Omsk","Asia/Novosibirsk","Asia/Barnaul","Asia/Tomsk","Asia/Novokuznetsk","Asia/Krasnoyarsk","Asia/Irkutsk","Asia/Chita","Asia/Yakutsk","Asia/Khandyga","Asia/Vladivostok","Asia/Ust-Nera","Asia/Magadan","Asia/Sakhalin","Asia/Srednekolymsk","Asia/Kamchatka","Asia/Anadyr"]},
  {"code":"RW","name":"Rwanda","currencies":["RWF"],"locale":"rw-RW","timeZones":["Africa/Kigali"]},
  {"code":"WS","name":"Samoa","currencies":["WST"],"locale":"sm-WS","timeZones":["Pacific/Apia"]},
  {"code":"SM","name":"San Marino","currencies":["EUR"],"locale":"it-SM","timeZones":["Europe/San_Marino"]},
  {"code":"ST","name":"São Tomé & Príncipe","currencies":["STN"],"locale":"pt-ST","timeZones":["Africa/Sao_Tome"]},
  {"code":"SA","name":"Saudi Arabia","currencies":["SAR"],"locale":"ar-SA","timeZones":["Asia/Riyadh"]},
  {"code":"SN","name":"Senegal","currencies":["XOF"],"locale":"wo-SN","timeZones":["Africa/Dakar"]},
  {"code":"RS","name":"Serbia","currencies":["RSD"],"locale":"sr-RS","timeZones":["Europe/Belgrade"]},
  {"code":"SC","name":"Seychelles","currencies":["SCR"],"locale":"fr-SC","timeZones":["Indian/Mahe"]},
  {"code":"SL","name":"Sierra Leone","currencies":["SLE"],"locale":"en-SL","timeZones":["Africa/Freetown"]},
  {"code":"SG","name":"Singapore","currencies":["SGD"],"locale":"en-SG","timeZones":["Asia/Singapore"]},
  {"code":"SX","name":"Sint Maarten","currencies":["XCG"],"locale":"en-SX","timeZones":["America/Lower_Princes"]},
  {"code":"SK","name":"Slovakia","currencies":["EUR"],"locale":"sk-SK","timeZones":["Europe/Bratislava"]},
  {"code":"SI","name":"Slovenia","currencies":["EUR"],"locale":"sl-SI","timeZones":["Europe/Ljubljana"]},
  {"code":"SB","name":"Solomon Islands","currencies":["SBD"],"locale":"en-SB","timeZones":["Pacific/Guadalcanal"]},
  {"code":"SO","name":"Somalia","currencies":["SOS"],"locale":"so-SO","timeZones":["Africa/Mogadishu"]},
  {"code":"ZA","name":"South Africa","currencies":["ZAR"],"locale":"en-ZA","timeZones":["Africa/Johannesburg"]},
  {"code":"GS","name":"South Georgia & South Sandwich Islands","currencies":["GBP"],"locale":"en-GS","timeZones":["Atlantic/South_Georgia"]},
  {"code":"KR","name":"South Korea","currencies":["KRW"],"locale":"ko-KR","timeZones":["Asia/Seoul"]},
  {"code":"SS","name":"South Sudan","currencies":["SSP"],"locale":"ar-SS","timeZones":["Africa/Juba"]},
  {"code":"ES","name":"Spain","currencies":["EUR"],"locale":"es-ES","timeZones":["Europe/Madrid","Africa/Ceuta","Atlantic/Canary"]},
  {"code":"LK","name":"Sri Lanka","currencies":["LKR"],"locale":"si-LK","timeZones":["Asia/Colombo"]},
  {"code":"BL","name":"St. Barthélemy","currencies":["EUR"],"locale":"fr-BL","timeZones":["America/St_Barthelemy"]},
  {"code":"SH","name":"St. Helena","currencies":["SHP"],"locale":"en-SH","timeZones":["Atlantic/St_Helena"]},
  {"code":"KN","name":"St. Kitts & Nevis","currencies":["XCD"],"locale":"en-KN","timeZones":["America/St_Kitts"]},
  {"code":"LC","name":"St. Lucia","currencies":["XCD"],"locale":"en-LC","timeZones":["America/St_Lucia"]},
  {"code":"MF","name":"St. Martin","currencies":["EUR"],"locale":"fr-MF","timeZones":["America/Marigot"]},
  {"code":"PM","name":"St. Pierre & Miquelon","currencies":["EUR"],"locale":"fr-PM","timeZones":["America/Miquelon"]},
  {"code":"VC","name":"St. Vincent & Grenadines","currencies":["XCD"],"locale":"en-VC","timeZones":["America/St_Vincent"]},
  {"code":"SD","name":"Sudan","currencies":["SDG"],"locale":"ar-SD","timeZones":["Africa/Khartoum"]},
  {"code":"SR","name":"Suriname","currencies":["SRD"],"locale":"nl-SR","timeZones":["America/Paramaribo"]},
  {"code":"SJ","name":"Svalbard & Jan Mayen","currencies":["NOK"],"locale":"nb-SJ","timeZones":["Arctic/Longyearbyen"]},
  {"code":"SE","name":"Sweden","currencies":["SEK"],"locale":"sv-SE","timeZones":["Europe/Stockholm"]},
  {"code":"CH","name":"Switzerland","currencies":["CHF"],"locale":"de-CH","timeZones":["Europe/Zurich"]},
  {"code":"SY","name":"Syria","currencies":["SYP"],"locale":"ar-SY","timeZones":["Asia/Damascus"]},
  {"code":"TW","name":"Taiwan","currencies":["TWD"],"locale":"zh-TW","timeZones":["Asia/Taipei"]},
  {"code":"TJ","name":"Tajikistan","currencies":["TJS"],"locale":"tg-TJ","timeZones":["Asia/Dushanbe"]},
  {"code":"TZ","name":"Tanzania","currencies":["TZS"],"locale":"sw-TZ","timeZones":["Africa/Dar_es_Salaam"]},
  {"code":"TH","name":"Thailand","currencies":["THB"],"locale":"th-TH","timeZones":["Asia/Bangkok"]},
  {"code":"TL","name":"Timor-Leste","currencies":["USD"],"locale":"pt-TL","timeZones":["Asia/Dili"]},
  {"code":"TG","name":"Togo","currencies":["XOF"],"locale":"fr-TG","timeZones":["Africa/Lome"]},
  {"code":"TK","name":"Tokelau","currencies":["NZD"],"locale":"tkl-TK","timeZones":["Pacific/Fakaofo"]},
  {"code":"TO","name":"Tonga","currencies":["TOP"],"locale":"to-TO","timeZones":["Pacific/Tongatapu"]},
  {"code":"TT","name":"Trinidad & Tobago","currencies":["TTD"],"locale":"en-TT","timeZones":["America/Port_of_Spain"]},
  {"code":"TN","name":"Tunisia","currencies":["TND"],"locale":"ar-TN","timeZones":["Africa/Tunis"]},
  {"code":"TR","name":"Türkiye","currencies":["TRY"],"locale":"tr-TR","timeZones":["Europe/Istanbul"]},
  {"code":"TM","name":"Turkmenistan","currencies":["TMT"],"locale":"tk-TM","timeZones":["Asia/Ashgabat"]},
  {"code":"TC","name":"Turks & Caicos Islands","currencies":["USD"],"locale":"en-TC","timeZones":["America/Grand_Turk"]},
  {"code":"TV","name":"Tuvalu","currencies":["AUD"],"locale":"tvl-TV","timeZones":["Pacific/Funafuti"]},
  {"code":"UM","name":"U.S. Outlying Islands","currencies":["USD"],"locale":"en-UM","timeZones":["Pacific/Midway","Pacific/Wake"]},
  {"code":"VI","name":"U.S. Virgin Islands","currencies":["USD"],"locale":"en-VI","timeZones":["America/St_Thomas"]},
  {"code":"UG","name":"Uganda","currencies":["UGX"],"locale":"sw-UG","timeZones":["Africa/Kampala"]},
  {"code":"UA","name":"Ukraine","currencies":["UAH"],"locale":"uk-UA","timeZones":["Europe/Simferopol","Europe/Kyiv"]},
  {"code":"AE","name":"United Arab Emirates","currencies":["AED"],"locale":"ar-AE","timeZones":["Asia/Dubai"]},
  {"code":"GB","name":"United Kingdom","currencies":["GBP"],"locale":"en-GB","timeZones":["Europe/London"]},
  {"code":"US","name":"United States","currencies":["USD"],"locale":"en-US","timeZones":["America/New_York","America/Detroit","America/Kentucky/Louisville","America/Kentucky/Monticello","America/Indiana/Indianapolis","America/Indiana/Vincennes","America/Indiana/Winamac","America/Indiana/Marengo","America/Indiana/Petersburg","America/Indiana/Vevay","America/Chicago","America/Indiana/Tell_City","America/Indiana/Knox","America/Menominee","America/North_Dakota/Center","America/North_Dakota/New_Salem","America/North_Dakota/Beulah","America/Denver","America/Boise","America/Phoenix","America/Los_Angeles","America/Anchorage","America/Juneau","America/Sitka","America/Metlakatla","America/Yakutat","America/Nome","America/Adak","Pacific/Honolulu"]},
  {"code":"UY","name":"Uruguay","currencies":["UYU"],"locale":"es-UY","timeZones":["America/Montevideo"]},
  {"code":"UZ","name":"Uzbekistan","currencies":["UZS"],"locale":"uz-UZ","timeZones":["Asia/Samarkand","Asia/Tashkent"]},
  {"code":"VU","name":"Vanuatu","currencies":["VUV"],"locale":"bi-VU","timeZones":["Pacific/Efate"]},
  {"code":"VA","name":"Vatican City","currencies":["EUR"],"locale":"it-VA","timeZones":["Europe/Vatican"]},
  {"code":"VE","name":"Venezuela","currencies":["VES"],"locale":"es-VE","timeZones":["America/Caracas"]},
  {"code":"VN","name":"Vietnam","currencies":["VND"],"locale":"vi-VN","timeZones":["Asia/Ho_Chi_Minh"]},
  {"code":"WF","name":"Wallis & Futuna","currencies":["XPF"],"locale":"fr-WF","timeZones":["Pacific/Wallis"]},
  {"code":"EH","name":"Western Sahara","currencies":["MAD"],"locale":"ar-EH","timeZones":["Africa/El_Aaiun"]},
  {"code":"YE","name":"Yemen","currencies":["YER"],"locale":"ar-YE","timeZones":["Asia/Aden"]},
  {"code":"ZM","name":"Zambia","currencies":["ZMW"],"locale":"en-ZM","timeZones":["Africa/Lusaka"]},
  {"code":"ZW","name":"Zimbabwe","currencies":["ZWG","USD"],"locale":"sn-ZW","timeZones":["Africa/Harare"]},
];
